import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GC Strapi Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} tailwind antialiased min-h-screen flex flex-col`}>
        <header className="bg-[#e7e7e7] h-[120px] flex items-center justify-around flex-none">
          <span>Guitar Center Header</span>
        </header>
        <main className="bg-white flex-auto">{children}</main>
        <footer className="bg-[#e7e7e7] h-[120px] flex items-center justify-around flex-none">
          <span>Guitar Center Header</span>
        </footer>
      </body>
    </html>
  );
}
